package ConnexOpenErp;


/**
* ConnexOpenErp/AchatVenteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public interface AchatVenteOperations 
{
  ConnexOpenErp.AchatVentePackage.Product[] listerProducts ();
  ConnexOpenErp.AchatVentePackage.Supplier[] listerSuppliers ();
} // interface AchatVenteOperations
