package ConnexOpenErp;


/**
* ConnexOpenErp/AchatVentePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public abstract class AchatVentePOA extends org.omg.PortableServer.Servant
 implements ConnexOpenErp.AchatVenteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("listerProducts", new java.lang.Integer (0));
    _methods.put ("listerSuppliers", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ConnexOpenErp/AchatVente/listerProducts
       {
         ConnexOpenErp.AchatVentePackage.Product $result[] = null;
         $result = this.listerProducts ();
         out = $rh.createReply();
         ConnexOpenErp.AchatVentePackage.ListeProductHelper.write (out, $result);
         break;
       }

       case 1:  // ConnexOpenErp/AchatVente/listerSuppliers
       {
         ConnexOpenErp.AchatVentePackage.Supplier $result[] = null;
         $result = this.listerSuppliers ();
         out = $rh.createReply();
         ConnexOpenErp.AchatVentePackage.ListeSupplierHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ConnexOpenErp/AchatVente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AchatVente _this() 
  {
    return AchatVenteHelper.narrow(
    super._this_object());
  }

  public AchatVente _this(org.omg.CORBA.ORB orb) 
  {
    return AchatVenteHelper.narrow(
    super._this_object(orb));
  }


} // class AchatVentePOA
