package ConnexOpenErp.AchatVentePackage;


/**
* ConnexOpenErp/AchatVentePackage/ListeProductHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

abstract public class ListeProductHelper
{
  private static String  _id = "IDL:ConnexOpenErp/AchatVente/ListeProduct:1.0";

  public static void insert (org.omg.CORBA.Any a, ConnexOpenErp.AchatVentePackage.Product[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConnexOpenErp.AchatVentePackage.Product[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ConnexOpenErp.AchatVentePackage.ProductHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ConnexOpenErp.AchatVentePackage.ListeProductHelper.id (), "ListeProduct", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConnexOpenErp.AchatVentePackage.Product[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ConnexOpenErp.AchatVentePackage.Product value[] = null;
    int _len0 = istream.read_long ();
    value = new ConnexOpenErp.AchatVentePackage.Product[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ConnexOpenErp.AchatVentePackage.ProductHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConnexOpenErp.AchatVentePackage.Product[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ConnexOpenErp.AchatVentePackage.ProductHelper.write (ostream, value[_i0]);
  }

}
