package ConnexOpenErp.AchatVentePackage;


/**
* ConnexOpenErp/AchatVentePackage/ListeProductHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public final class ListeProductHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnexOpenErp.AchatVentePackage.Product value[] = null;

  public ListeProductHolder ()
  {
  }

  public ListeProductHolder (ConnexOpenErp.AchatVentePackage.Product[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnexOpenErp.AchatVentePackage.ListeProductHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnexOpenErp.AchatVentePackage.ListeProductHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnexOpenErp.AchatVentePackage.ListeProductHelper.type ();
  }

}
