package ConnexOpenErp.AchatVentePackage;


/**
* ConnexOpenErp/AchatVentePackage/ListeSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public final class ListeSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnexOpenErp.AchatVentePackage.Supplier value[] = null;

  public ListeSupplierHolder ()
  {
  }

  public ListeSupplierHolder (ConnexOpenErp.AchatVentePackage.Supplier[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnexOpenErp.AchatVentePackage.ListeSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnexOpenErp.AchatVentePackage.ListeSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnexOpenErp.AchatVentePackage.ListeSupplierHelper.type ();
  }

}
