package ConnexOpenErp.AchatVentePackage;


/**
* ConnexOpenErp/AchatVentePackage/Product.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public final class Product implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public double qtyAvailable = (double)0;
  public double prixVente = (double)0;

  public Product ()
  {
  } // ctor

  public Product (int _id, String _name, double _qtyAvailable, double _prixVente)
  {
    id = _id;
    name = _name;
    qtyAvailable = _qtyAvailable;
    prixVente = _prixVente;
  } // ctor

} // class Product
