package ConnexOpenErp.AchatVentePackage;


/**
* ConnexOpenErp/AchatVentePackage/Supplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConnexionOpenErp.idl
* mardi 16 décembre 2014 17 h 27 CET
*/

public final class Supplier implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;

  public Supplier ()
  {
  } // ctor

  public Supplier (int _id, String _name)
  {
    id = _id;
    name = _name;
  } // ctor

} // class Supplier
